BULK INSERT Countries
FROM 'C:\Users\enzoe\Documents\GEODATASOURCE-CITIES-FREE.TXT\GEODATASOURCE-COUNTRY.TXT'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '\n'
)
GO

BULK INSERT Cities
FROM 'C:\Users\enzoe\Documents\GEODATASOURCE-CITIES-FREE.TXT\GEODATASOURCE-CITIES-FREE.TXT'
WITH
(
    FIRSTROW = 2,
    FIELDTERMINATOR = '\t',
    ROWTERMINATOR = '\n'
)
GO

SELECT Username FROM Players WHERE First_name = 'enzo';

SELECT COUNTRY_NAME FROM Countries;

